FROM centos
RUN mkdir /opt/tomcat/
WORKDIR /opt/tomcat
ADD https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.6/bin/apache-tomcat-10.0.6.tar.gz .
RUN tar -xvf apache-tomcat-10.0.6.tar.gz
RUN mv apache-tomcat-10.0.6/* /opt/tomcat
RUN yum install java -y
RUN java -version
WORKDIR /opt/tomcat/webapps
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
