FROM centos
RUN mkdir /opt/tomcat/
WORKDIR /opt/tomcat
ADD https://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.tar.gz
RUN tar -xvf apache-tomcat-9.0.45.tar.gz
RUN mv apache-tomcat-9.0.45.tar.gz/* /opt/tomcat/.
RUN yum install java -y
RUN java -version
WORKDIR /opt/tomcat/webapps
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
