FROM tomcat
RUN sed -i '/<\tomcat-users>/ i\user username="admin" password="password" roles="admin-gui,manager-gui">/' /usr/local/tomcat/conf/tomcat-users.xml
#COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY *.war /usr/local/tomcat/webapps/*.war
